spring.application.name=scraper

server.port=8080

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/scraper_gateway

# API JSON style
spring.jackson.property-naming-strategy=SNAKE_CASE
