spring.application.name=scraper

server.port=8080

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:mongo@mongodb:27017/scraper_gateway?authSource=admin}
spring.mongodb.uri=${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://admin:mongo@mongodb:27017/scraper_gateway?authSource=admin}}

# API JSON style
spring.jackson.property-naming-strategy=SNAKE_CASE
